### PR TITLE
Removing respond-ng import

### PR DESCRIPTION
**Pull request by onlyann**
The store example test file requires this dependency.

### CODE REVIEW

**Comment by littleStudent** [comment]
Thx for noticing.
ng-respond is not really needed. Could you instead just remove line 7 in shop.spec.ts please?
```import RESPOND_PROVIDERS, {Respond} from 'respond-ng';```
It is unused!

**Comment by littleStudent** [comment]
can you also remove `"respond-ng": "0.0.2",` from package.json again?

**Comment by onlyann** [comment]
Sorry for the history mess. It's the first time I perform a pull request.

**Comment by btroncone** [comment]
Looks great, thanks!

**Pull request merged**
